### ISSUE TITLE
Fix dependency on njson/core

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nactivitypub#1]
This fails to load with a recent njson because `njson/core` was removed.

`nactivitypub.asd` says:

```
  ;; FIXME: Depending on njson/core makes us lighter on dependencies
  ;; users of the library don't need, but forces us to load the actual
  ;; NJSON back-end, like njson/cl-json, elsewhere. Is that a
  ;; reasonable trade-off?
```

@aartaka ?

**Comment by aartaka** [comment]
Yes, simply replace it with `njson`!

**Comment by Ambrevar** [comment]
Done in 03505467029134cb8912c63df0840e3c98bd24a4.  Is that good enough?

**Comment by aartaka** [comment]
> Done in [0350546](https://github.com/atlas-engineer/nactivitypub/commit/03505467029134cb8912c63df0840e3c98bd24a4). Is that good enough?

Yes, just fine!
